### ISSUE TITLE
[Nest] 3488   - 10/05/2019, 10:23:50 AM   [TypeOrmModule] Unable to connect to the database. Retrying (9)... +3010ms Error: No connection options were found in any of configurations file.     at ConnectionOptionsReader.<anonymous> (C:\Users\lalith\my-nest-project\node_modules\typeorm\connection\ConnectionOptionsReader.js:34:35)     at step (C:\Users\lalith\my-nest-project\node_modules\tslib\tslib.js:136:27)     at Object.next (C:\Users\lalith\my-nest-project\node_modules\tslib\tslib.js:117:57)     at fulfilled (C:\Users\lalith\my-nest-project\node_modules\tslib\tslib.js:107:62) [Nest] 3488   - 10/05/2019, 10:23:50 AM   [ExceptionHandler] No connection options were found in any of configurations file. +3ms

### ISSUE THREAD

**Issue by nitin28061996** [naimjeem/nestjs-mysql-crud-api#1]

**Comment by nitin28061996** [comment]
Error: No connection options were found in any of configurations file.     at ConnectionOptionsReader.<anonymous> (C:\Users\lalith\my-nest-project\node_modules\typeorm\connection\ConnectionOptionsReader.js:34:35)     at step (C:\Users\lalith\my-nest-project\node_modules\tslib\tslib.js:136:27)     at Object.next (C:\Users\lalith\my-nest-project\node_modules\tslib\tslib.js:117:57)     at fulfilled (C:\Users\lalith\my-nest-project\node_modules\tslib\tslib.js:107:62) [Nest] 3488   - 10/05/2019, 10:23:50 AM   [ExceptionHandler] No connection options were found in any of configurations file. +3ms
